In [1]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np
from collections import Counter
iris=load_iris()
print(iris.data[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [2]:
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2,random_state=42)

In [13]:
def ecludean_distance(x1,x2):
  return np.sqrt(np.sum(x1-x2)**2)

class KNN:
  def __init__(self,k=3):
    self.k = k
    self.X_train = None
    self.y_train = None

  def fit(self,X,y):
    self.X_train = X
    self.y_train = y

  def _predict(self,X):
    return [self.predict(x) for x in X]

  def predict(self,x):
    distance=[ecludean_distance(x,x_train) for x_train in X_train ]

    K_indices=np.argsort(distance)[:self.k]
    k_nearest_labels=[self.y_train[i] for i in K_indices]
    most_common = Counter(k_nearest_labels).most_common(1)
    return most_common[0][0]



In [15]:
knn = KNN(k=3)
knn.fit(X_train, y_train)

# Predict
predictions = knn._predict(X_test)
print(predictions)
print("Accuracy:", accuracy_score(y_test, predictions))

[np.int64(1), np.int64(1), np.int64(2), np.int64(1), np.int64(2), np.int64(0), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(0), np.int64(0), np.int64(0), np.int64(0), np.int64(2), np.int64(2), np.int64(1), np.int64(1), np.int64(2), np.int64(0), np.int64(2), np.int64(0), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(2), np.int64(0), np.int64(0)]
Accuracy: 0.9
